### ISSUE TITLE
No SDR prices available anymore

### ISSUE THREAD

**Issue by StrathCole** [classic-terra/oracle-feeder#28]
It seems, exchangerate.host changed their policy to closed usage. All (or at least most) oracle price servers who used the service, don't have an API key, but calling the api without key is no longer possible.

So the chain currently has no SDR price anymore.
And as it's the core currency for the MM … 🤷‍♂️
It stopped working ~ Block 14723744. Which was ~2 days ago.

You can see that https://terra-classic-lcd.publicnode.com/terra/oracle/v1beta1/denoms/exchange_rates has no usdr in the exchange rates anymore.
Also `curl -s http://127.0.0.1:8532/latest | jq '.prices[] | select(.denom == "SDR")'` on the oracle server returns an empty result.

It also means that stable-to-stable swaps are currently non-functional.

**Comment by aeuser999** [comment]
**Comments:**
Just a note though that there are other SDR Providers (FastForex is $9 a month - was just added in 3 months back to help keep SDR pricing from a single source of failure, also the other fiat providers were also fixed to work for SDR pricing as well [although a bit higher than $9 a month]).

What is interesting is that many are still voting with SDR sources:
- [See All Individual Exchange Rate Votes For Validators](https://aeuser999.github.io/terra-retrieve-oracle-vote-info/terra-retrieve-oracle-vote-info.html)
     - For instance:  blocks:  14747800 - 14747803

Yet, it is seeing 0.0 as an actual price rather than an abstain (so that probably needs to be fixed):
- [Aggregate Vote Example With SDR showing 0.0000000000 currently](https://terra-classic-lcd.publicnode.com/terra/oracle/v1beta1/validators/aggregate_votes)
- Should see a non-positive integer as abstaining for that denomination:
     - https://github.com/classic-terra/core/blob/main/x/oracle/spec/03_end_block.md#tally-exchange-rate-votes
     - https://classic-docs.terra.money/docs/develop/module-specifications/spec-oracle.html#abstaining-from-voting
- [For some reason it sees 0.0 as not abstaining - if they had, it would appear that the other positive value SDR pricing should have come through](https://terra-classic-lcd.publicnode.com/terra/oracle/v1beta1/validators/aggregate_votes)
- Somewhere in Code, Type, or sdk.Dec and IsPositive()?:
     - https://github.com/classic-terra/core/blob/main/x/oracle/abci.go#L55-L58
     - https://github.com/classic-terra/core/blob/main/x/oracle/keeper/ballot.go#L26-L30
     - https://github.com/classic-terra/core/blob/main/x/oracle/tally.go#L23-L32

**A Potential Code Update**
Here is an adjustment to make ExchangeRate work (both non-API and API):
- [Adjust ExchangeRate.tx and updated default-test.js](https://github.com/aeuser999/test_oracle_feeder/commit/141872a89fb5ddeb5b915c8d8b8380600eec02a5)
     - Note:  just needs the testing comments removed (which have no indentation to make identification easier), and that along with the changes mentioned [earlier here](https://github.com/classic-terra/oracle-feeder/issues/24#issuecomment-1729646414), and final testing on your side, and it should be good (feel free to use any of the code, and/or change it, or improve it).
     - tagging @nghuyenthevinh2000  and @inon-man incase it looks helpful
     
I hope that helps out a little bit, and that you each have a great day today :)

**Comment by aeuser999** [comment]
@StrathCole :  here is a fix that works with ExchangeRate both without api key and with api key (tested it), just did not create a pull request (although you can pull the whole repo and test with, just rename default-test.js to default.js): 
- https://github.com/aeuser999/test_oracle_feeder/commit/141872a89fb5ddeb5b915c8d8b8380600eec02a5
